'use client';
import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("ar");

  const translations = {
    en: {
      map: "Search by map",
      list: "Search by list",
      signIn: "Sign In",
      signOut: "Sign Out",
      addProperty: "Add Property",
      language: "العربية",
      menu: "Menu",
      mobile: "Mobile",
      password: "Password",
      invalidCredentials: "Invalid mobile or password",
      welcome: "Welcome",
      forgotPassword: "Forgot Password?",
      dontHaveAccount: "Don't have an account?",
      signUp: "Sign Up",
      firstName: "First Name",
      lastName: "Last Name",
      confirmPassword: "Confirm Password",
      passwordsDontMatch: "Passwords don't match",
      invalidMobile: "Invalid Syrian mobile number format",
      signupError: "Signup failed",
      networkError: "Network error",
      loading: "Processing...",
      alreadyHaveAccount: "Already have an account?",
      signinAfterSignupFailed: 'Signup successful! Please sign in',
      dashboard: "Dashboard",
      welcomeBack: "Welcome Back",
      mapView: "Map View",
      satelliteView: "Satellite View",
      governorates: "Syrian Governorates",
      loadingMap: "Loading map...",
      profileSettings: 'Profile Settings',
      firstName: 'First Name',
      lastName: 'Last Name',
      mobileNumber: 'Mobile Number',
      profileImage: 'Profile Image URL',
      updateProfile: 'Update Profile',
      profileUpdated: 'Profile updated successfully!',
      updateError: 'Update failed. Please try again.',
      networkError: 'Network error. Please check your connection.',
      profileSettings: 'Profile Settings',
      firstName: 'First Name',
      lastName: 'Last Name',
      mobileNumber: 'Mobile Number',
      changeImage: 'Change Image',
      imageFormats: 'JPG, PNG up to 5MB',
      updateProfile: 'Update Profile',
      profileUpdated: 'Profile updated successfully!',
      updateError: 'Update failed. Please try again.',
      networkError: 'Network error. Please check your connection.',
      uploadError: 'Image upload failed. Please try again.',
      updating: 'Updating...',
      yourProfile: 'Your Profile',
      profileDesc: 'View and edit your personal information',
      manageProfile: 'Manage Profile',
      yourListings: 'Your Listings',
      listingsDesc: 'Manage your property listings',
      viewListings: 'View Listings',
      subscription: 'Subscription',
      subscriptionDesc: 'Manage your subscription plan',
      viewPlan: 'View Plan',
      dashboardDesc: 'Manage your account and listings from here',
      subscription: 'Subscription',
      freePlan: 'Free Plan',
      goldenPlan: 'Golden Plan',
      diamondPlan: 'Diamond Plan',
      freePlanDesc: 'Basic features',
      goldenPlanDesc: 'Enhanced visibility',
      diamondPlanDesc: 'Premium experience',
      currentPlan: 'Your Current Plan',
      upgrade: 'Upgrade Now',
      selectPlan: 'Select Plan',
      features: 'Features',
      subscriptionDesc: 'Choose the plan that works best for you. Upgrade or downgrade at any time.',
      liked: 'Liked',
      noLikedProperties: 'You have not liked any properties yet',
      browseProperties: 'Browse Properties',
      viewDetails: 'View Details',
      chat: 'Chats',
      noConversations: 'You have no messages yet',
      notifications: 'Notifications',
      markAllRead: 'Mark all as read',
      noNotifications: 'No notifications yet',
      viewAll: 'View all notifications',
      noNotificationsDesc: 'Your notifications will appear here when you have new activity.',
      featuredListings: 'Featured Listings',
      allListings: 'All Listings',
      viewDetails: 'View Details',
      viewAllProperties: 'View All Properties',
      bedrooms: 'Bedrooms',
      bathrooms: 'Bathrooms',
      area: 'Area',
      apartments: 'Apartments',
      villas: 'Villas',
      commercial: 'Commercial',
      land: 'Land',
      allProperties: 'All Properties',
      propertyImages: 'Add Images for the property',
      featured: 'Featured',
      loadMore: 'Load More',
      title: 'Property Title',
      price: 'Property Price',
      location: 'Property Address',
      propertyType: 'Property Type',
      apartment: 'Apartment',
      villa: 'Villa',
      office: 'Office',
      land: 'Land',
      description: 'Description',
      minPrice: "Min Price",
      maxPrice: "Max Price",
      bedrooms: "Bedrooms",
      propertyType: "Property Type",
      any: "Any",
      featuredOnly: "Featured Only",
      resetFilters: "Reset Filters",
      allListings: "All Listings",
      viewDetails: "View Details",
      noImage: "No Image",
      noPropertiesFound: "No properties found",
      clearFilters: "Clear Filters",
      bedroom: "Bed",
      bedrooms: "Beds",
      bathroom: "Bath",
      bathrooms: "Baths",
      filterListings: "Filter Listings",
      loginRequired: "Login Required",
      loginToViewListings: "Please log in to view all property listings",
      loginToSeeMore: "Log in to see all available properties",
      featuredSample: "Featured Property Sample",
      contractType: "Contract Type",
      rent: "Rent",
      sale: "Sale",
      mortgage: "Mortgage",
      ownershipType: "Ownership Type",
      green_deed: "Green Deed (طابو أخضر)",
      white_deed: "White Deed (طابو أبيض)",
      court_decision: "Court Decision (حكم محكمة)",
      notary: "Notary (كاتب عدل)",
      emiri: "Emiri (أميري)",
      reform: "Reform (إصلاح)",
      charitable_endowment: "Charitable Endowment (وقف خيري)",
      lineage_endowment: "Lineage Endowment (وقف ذري)",
      meter: 'm²',
      governorate: "Governorate",
      city: "City",
      district: "District",
      selectGovernorate: "Select Governorate",
      selectCity: "Select City",
      selectDistrict: "Select District",
      locationDetails: "Location Details",
      viewDetails: 'View Property',
      pdetails: 'Property Details',
      propertyAge: "Property Age",
      airConditioning: "Air Conditioning",
      privateParking: "Private Parking",
      entrances: "Number of Entrances",
      electricity: "Electricity",
      water: "Water",
      violations: "Violations Exist",
      rooftopOwnership: "Rooftop Ownership",
      video: "Property Video",
      yes: "Yes",
      no: "No",
      none: "None",
      normalSplit: "Normal Split AC",
      inverterSplit: "Inverter Split AC",
      central: "Central AC",
      concealed: "Concealed AC",
      windowAC: "Window AC",
      desertAC: "Desert AC",
      noElectricity: "No Electricity",
      solarPanels: "Solar Panels",
      amberSubscription: "Amber Subscription",
      govElectricity: "Government Electricity",
      noWater: "No Water",
      nonDrinkable: "Non-Drinkable",
      drinkable: "Drinkable",
      shared: "Shared",
      private: "Private",
      videoUploadError: "Failed to upload video",




    },
    ar: {
      map: "البحث بالخريطة",
      list: "البحث بالقائمة",
      signIn: "تسجيل الدخول",
      signOut: "تسجيل الخروج",
      addProperty: "إضافة عقار",
      language: "English",
      menu: "القائمة",
      mobile: "رقم الجوال",
      password: "كلمة المرور",
      invalidCredentials: "رقم الجوال أو كلمة المرور غير صحيحة",
      welcome: "مرحباً",
      forgotPassword: "نسيت كلمة المرور؟",
      dontHaveAccount: "ليس لديك حساب؟",
      signUp: "تسجيل",
      firstName: "الاسم الأول",
      lastName: "الاسم الأخير",
      confirmPassword: "تأكيد كلمة المرور",
      passwordsDontMatch: "كلمات المرور غير متطابقة",
      invalidMobile: "صيغة رقم الجوال السوري غير صالحة",
      signupError: "فشل إنشاء الحساب",
      networkError: "خطأ في الشبكة",
      loading: "جاري المعالجة...",
      alreadyHaveAccount: "هل لديك حساب بالفعل؟",
      signinAfterSignupFailed: 'تم التسجيل بنجاح! يرجى تسجيل الدخول',
      dashboard: "لوحة التحكم",
      welcomeBack: "أهلا بك يا ",
      mapView: "عرض الخريطة",
      satelliteView: "عرض الأقمار الصناعية",
      governorates: "المحافظات السورية",
      loadingMap: "جاري تحميل الخريطة...",
      profileSettings: 'إعدادات الملف الشخصي',
      firstName: 'الاسم الأول',
      lastName: 'الاسم الأخير',
      mobileNumber: 'رقم الهاتف',
      profileImage: 'رابط صورة الملف الشخصي',
      updateProfile: 'تحديث الملف الشخصي',
      profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
      updateError: 'فشل التحديث. يرجى المحاولة مرة أخرى.',
      networkError: 'خطأ في الشبكة. يرجى التحقق من اتصالك.',
      profileSettings: 'إعدادات الملف الشخصي',
      firstName: 'الاسم الأول',
      lastName: 'الاسم الأخير',
      mobileNumber: 'رقم الهاتف',
      changeImage: 'تغيير الصورة',
      imageFormats: 'JPG, PNG بحد أقصى 5MB',
      updateProfile: 'تحديث الملف الشخصي',
      profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
      updateError: 'فشل التحديث. يرجى المحاولة مرة أخرى.',
      networkError: 'خطأ في الشبكة. يرجى التحقق من اتصالك.',
      uploadError: 'فشل تحميل الصورة. يرجى المحاولة مرة أخرى.',
      updating: 'جارٍ التحديث...',
      yourProfile: 'ملفك الشخصي',
      profileDesc: 'عرض وتعديل معلوماتك الشخصية',
      manageProfile: 'إدارة الملف',
      yourListings: 'عقاراتك',
      listingsDesc: 'إدارة قوائم العقارات الخاصة بك',
      viewListings: 'عرض العقارات',
      subscription: 'الاشتراك',
      subscriptionDesc: 'إدارة خطة الاشتراك الخاصة بك',
      viewPlan: 'عرض الخطة',
      dashboardDesc: 'ادخل حسابك وعقاراتك من هنا',
      subscription: 'الاشتراك',
      freePlan: 'الباقة المجانية',
      goldenPlan: 'الباقة الذهبية',
      diamondPlan: 'الباقة الماسية',
      freePlanDesc: 'ميزات أساسية',
      goldenPlanDesc: 'ظهور مميز',
      diamondPlanDesc: 'تجربة مميزة',
      currentPlan: 'باقتك الحالية',
      upgrade: 'ترقية الآن',
      selectPlan: 'اختر الباقة',
      features: 'المميزات',
      subscriptionDesc: 'اختر الباقة التي تناسبك. يمكنك الترقية أو التخفيض في أي وقت.',
      liked: 'المفضلة',
      noLikedProperties: 'لم تقم بإضافة أي عقارات إلى المفضلة بعد',
      browseProperties: 'تصفح العقارات',
      viewDetails: 'عرض التفاصيل',
      chat: ' المحادثات',
      noConversations: 'لا توجد لديك أي محادثات بعد',
      notifications: 'الإشعارات',
      markAllRead: 'تحديد الكل كمقروء',
      noNotifications: 'لا توجد إشعارات بعد',
      viewAll: 'عرض جميع الإشعارات',
      noNotificationsDesc: 'ستظهر إشعاراتك هنا عندما يكون لديك نشاط جديد.',

      featuredListings: 'العروض المميزة',
      allListings: 'جميع العقارات',
      viewDetails: 'عرض التفاصيل',
      viewAllProperties: 'عرض جميع العقارات',
      bedrooms: 'غرف النوم',
      bathrooms: 'الحمامات',
      area: 'المساحة بالمتر المربع (م²)',
      apartments: 'شقق',
      villa: 'فيلا',
      shop: 'محل',
      office: 'مكتب',
      full_floor: 'طابق كامل',
      full_building: 'مبنى كامل',
      house: 'بيت',
      arabian_house: 'بيت عربي',
      farm: 'مزرعة',
      warehouse: 'مستودع',
      seaside_chalet: 'شاليه على البحر',
      palace: 'قصر',
      showroom: 'معرض',
      wedding_hall: 'قاعة افراح',
      land: 'أرض',
      allProperties: 'جميع العقارات',
      propertyImage: 'صورة العقار',
      featured: 'مميز',
      loadMore: 'تحميل المزيد',
      title: 'اسم العقار',
      price: 'سعر العقار',
      location: ' عنوان العقار بالتفصيل',
      propertyType: 'نوع العقار',
      apartment: 'شقة',
      description: 'وصف العقار',
      minPrice: "أقل سعر",
      maxPrice: "أعلى سعر",
      bedrooms: "غرف النوم",
      propertyType: "نوع العقار",
      any: "أي",
      featuredOnly: "المميزة فقط",
      resetFilters: "إعادة تعيين الفلاتر",
      allListings: "جميع العقارات",
      viewDetails: "عرض التفاصيل",
      noImage: "لا توجد صورة",
      noPropertiesFound: "لم يتم العثور على عقارات",
      clearFilters: "مسح الفلاتر",
      bedroom: "غرفة",
      bedrooms: "غرف النوم",
      bathrooms: "دورات المياه",
      filterListings: "تصفية القوائم",
      loginRequired: "تسجيل الدخول مطلوب",
      loginToViewListings: "يرجى تسجيل الدخول لعرض جميع قوائم العقارات",
      loginToSeeMore: "سجل الدخول لرؤية جميع العقارات المتاحة",
      featuredSample: "عقار مميز كمثال",
      contractType: "نوع العقد",
      rent: "إيجار",
      sale: "بيع",
      mortgage: "رهن",
      ownershipType: "نوع الملكية",
      green_deed: "طابو أخضر",
      white_deed: "طابو أبيض",
      court_decision: "حكم محكمة",
      notary: "كاتب عدل",
      emiri: "أميري",
      reform: "إصلاح",
      charitable_endowment: "وقف خيري",
      lineage_endowment: "وقف ذري",
      verifiedOnly: 'عقار موثق فقط',
      meter: 'م²',
      governorate: "المحافظة",
      city: "المدينة",
      district: "المنطقة",
      selectGovernorate: "اختر المحافظة",
      selectCity: "اختر المدينة",
      selectDistrict: "اختر المنطقة",
      locationDetails: "تفاصيل الموقع",
      propertyImages: 'صور العقار',
      max10Images: 'الحد الأعلى 10 صور',
      uploadImages: 'تحميل صور العقار',
      image: 'اضافة صور للعقار',
      noImages: 'لم يتم اضافة صور للعقار',
      coordinates: 'احداثيات العقار',
      selectLocation: 'قم باختيار موقع العقار الحغرافي',
      clickToPlace: 'اضغط على الخريطة لاختيار موقع العقار',
      viewDetails: 'عرض تفاصيل العقار',
      pdetails: 'تفاصيل العقار',
      propertyAge: "عمر العقار",
      airConditioning: "المكيفات",
      privateParking: "موقف سيارات خاص",
      entrances: "عدد مداخل البيت",
      electricity: "الكهرباء",
      water: "المياه",
      violations: "هل يوجد مخالفات على العقار",
      rooftopOwnership: "ملكية سطح العقار",
      video: "فيديو العقار",
      yes: "نعم",
      no: "لا",
      none: "لا يوجد",
      normalSplit: "سبليت عادي",
      inverterSplit: "سبليت إنفرتر",
      central: "مركزي",
      concealed: "مخفي",
      windowAC: "نافذة",
      desertAC: "صحراوي",
      noElectricity: "لا يوجد كهرباء",
      solarPanels: "طاقة شمسية",
      amberSubscription: "اشتراك أمبير",
      govElectricity: "كهرباء حكومية فقط",
      noWater: "لا يوجد مياه",
      nonDrinkable: "غير صالحة للشرب",
      drinkable: "صالحة للشرب",
      shared: "مشتركة",
      private: "خاصة",
      videoUploadError: "فشل تحميل الفيديو",
      messageOwner: "مراسلة صاحب العقار",
      contactOwner: 'التواصل',
      amenities: 'وسائل الراحة',
      ownershipDetails: 'تفاصيل الملكية',
      keyFeatures: 'مزايا العقار',
      whatsapp: 'المراسلة عبر الواتساب',
      propertyInformation: 'معلومات العقار',
      coins: 'عملة المنصة',
      new: 'جديد',
      totalListings: "جميع العروض",
      featuredListings: "العروض المميزة",
      coins: "العملات",
      notifications: "الاشعارات",
      views: "المشاهدات",
      leads: "العملاء",
      quickActions: "الوصول السريع",
      recentActivity: "الأنشطة الاخيرة",
      manageListings: "ادارة العروض",
      viewFeatured: "رؤية العقارات المميزة",
      buyCoins: "شراء المزيد من العملات",
      viewAll: "رؤية الجميع",
      last7Days: "اخر سبعة ايام",
      potentialBuyers: "عملاء محتملين",
      addProperty: "اضافة عقار",
      viewListings: "رؤية العروض",
      profileSettings: "إعدادات الحساب",
      liked: "الإعجابات",
      decorationType: "نوع الاكساء", 
      propertyStatus: "حالة العقار",
      media: "وسائط",
      featuredAdded: "تم ترويج العقار",
      coinsAdded: "تم شراء عملات منصة",
      viewAllActivity: "رؤية جميع الانشطة",
      rentPeriod: 'مدة الأجار',
      daily: 'يومي',
      weekly: 'اسبوعي',
      yearly : 'سنوي',
      monthly : 'شهري',
      rentPrice : 'الأجار (بالدولار الامريكي)',
      insufficientCoins : 'عملات غير كافية',
      coinsAvailable:'العملات المتوفرة',
      includeVideo: 'اضافة فيديو',
      uploadVideo: 'تحميل فيديو',
      hideAdvancedFilters: 'اخفاء الفلاتر المتقدمة',
      showAdvancedFilters: 'إظهار الفلاتر المتقدمة',
      priceRange : 'المدى السعري',
      advancedFilters : 'الفلاتر المتقدمة',
      areaRange: 'مدى المساحة',
      properties : 'العقارات',
      noPropertiesDescription: 'جرب تعديل الفلاتر لرؤية العقارات',
      maxPricePlaceholder: 'الحد الأعلى',
      minPricePlaceholder: 'الحد الأدنى',
      maxArea : 'الحد الأعلى',
      minArea: 'الحد الأدنى',
      updateProperty: 'تحديث العقار',
      updating : 'جاري التحديث',
      videoUploaded : 'فيديو مرفوع',
      delete : 'حذف',
      edit:'تعديل',
      share:'مشاركة العقار'


    }
  };

  const toggleLanguage = () => {
    setLanguage(prevLang => prevLang === "en" ? "ar" : "en");
  };

  return (
    <LanguageContext.Provider value={{ language, translations, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};